version: '3'

services:
  teams-presence-mqtt:
    build: .
    env_file:
      - .env
    hostname: teamsmqtt
    container_name: teamsmqtt
    restart: always
  nginx-self-signed:
    build: './nginx'
    ports: 
      - "3080:80"
      - "3443:443"
    container_name: nginx-self-signed
    hostname: nginx-self-signed
    restart: always
